# Generated by Django 3.2.9 on 2021-11-11 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('dob', models.DateField()),
                ('house_no', models.PositiveIntegerField()),
                ('house_name', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=50)),
                ('pincode', models.PositiveIntegerField()),
                ('district', models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), (' Ernakulam', ' Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), (' Kozhikode', ' Kozhikode'), ('Wayanadu', 'Wayanadu'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default='Malappuram', max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('adhar_no', models.PositiveIntegerField()),
                ('whatsapp_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('any_proof', models.FileField(upload_to='proof_user')),
                ('bank_account_no', models.PositiveIntegerField(blank=True, null=True)),
                ('ifsc_code', models.PositiveIntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(default='state bank of india', max_length=40)),
                ('bank_branch', models.CharField(default='oorakam', max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('appruve', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('image', models.ImageField(default='default.jpg', upload_to='images')),
                ('user_type', models.CharField(choices=[('ward_member', 'ward_member'), ('staff', 'staff'), ('public', 'public')], default='public', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
