# Generated by Django 3.2.9 on 2021-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_details_ifsc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.PositiveIntegerField()),
                ('ward_name', models.CharField(max_length=40)),
            ],
        ),
    ]
