# Generated by Django 3.2.9 on 2021-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='house_no',
            field=models.CharField(max_length=50),
        ),
    ]
