# Generated by Django 4.0.2 on 2022-04-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_register_id_alter_user_details_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.AlterField(
            model_name='register',
            name='user_type',
            field=models.CharField(choices=[('staff', 'staff'), ('public', 'public')], default='public', max_length=20),
        ),
    ]
