# Generated by Django 4.0.2 on 2022-04-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_delete_ward_alter_register_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Details',
        ),
    ]
