# Generated by Django 4.0.2 on 2022-04-08 09:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0002_addcomplaint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addcomplaint',
            new_name='complaintss',
        ),
    ]
