# Generated by Django 4.0.2 on 2022-04-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_rename_addcomplaint_complaintss'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintss',
            name='phoneno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
